config/routes.rb
Rails.application.routes.draw do
  #get 'blogs/index'
  get '/blogs', to: 'blogs#index'
  resources :blogs do
  collection do
      post :confirm
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
   validates :title, :content, presence: true
   # has_any :favorites, dependent: :destroy
   # has_many :favorite_users, through: :favprite, souce: :user
  # belong_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
    before_action :set_blog, only: [:show, :edit, :update, :destroy]
  # lister les blog avec action index et remplir index.thml.erb
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end


  def create
    # pour remplacer @blog et @blog.user_id
   @blog = current_user.blogs.build(blog_params)
    #@blog = Blog.new(blog_params)
    # insert the vlue of forreign key
    #@blog.user_id = current_user.id
    if params[:back]
      render :new
    else
      if @blog.save
        redirect_to blogs_path, notice: "I have created a blog!"
      else
        render :new
      end
    end
  end


  # show action when show is called new.html is also called
  def show
    #@blog = Blog.find(params[:id])
  end

  def edit
     #@blog = Blog.find(params[:id])
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"I deleted the blog!"
  end


  def update
    #@blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "I edited the blog!"
    else
      render :edit
    end
  end

  def confirm
# pour remplacer @blog et @blog.user_id
  #  @blog = current_user.blogs.build(blog_params)
  @blog = current_user.blogs.build(blog_params)
    #@blog = Blog.new(blog_params)
    # insert value forreign key
    #@blog.user_id = current_user.id
    render :new if @blog.invalid?
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :content)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true ,url: choose_new_or_edit ) do |form| %>

  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>There are errors.</h2>
      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>
<%= link_to "Blog list画面にもどる", blogs_path %>

app/views/blogs/confirm.html.erb
<h3>Send with the following contents.</h3>
<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <p>Title:<%= @blog.title %></p>
  <p>Text:<%= @blog.content %></p>
  <%= form.submit  "register" %>
  <%= form.submit "Return", name: 'back' %>
<% end %>

app/views/blogs/edit.html.erb
<%= form_with(model: @blog, local: true) do |form| %>

  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
    <% end %>

app/views/blogs/index.html.erb
<h1>Blog list</h1>
<p><%= notice %></p>
<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
  </tr>
<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.id %></td>
    <td><%= blog.title %></td>
    <td><%= blog.content %></td>
     <!-- tres important -->
    <td><%= link_to 'Check the details', blog_path(blog.id) %></td>
    <td><%= link_to "Edit blog", edit_blog_path(blog.id) %></td>
    <td><%= link_to 'Delete blog', blog_path(blog.id), method: :delete,data: { confirm: 'Can I really edit it?' } %></td>

  </tr>
<% end %>
</table>
<br>

<%= link_to 'Post a new blog', new_blog_path %>

app/views/blogs/new.html.erb
<h2>Create a blog</h2>
<%= render 'form' %>

app/views/blogs/show.html.erb
<h1>Blog details screen</h1>
<p>Title: <%= @blog.title %></p>
<p>Content: <%= @blog.content %></p>





<%= form_with(model: @post, local: true) do |form| %>

  <div class="post_Autheur">
    <%= form.label :Autheur %>
    <%= form.text_field :Autheur %>
  </div>
  <div class="post_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>

    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleT</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>